# Project 2

#### Kyan and Rene

This will be a study on housing prices.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier, export_graphviz, plot_tree
from sklearn.model_selection import learning_curve, GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn import tree
from IPython.display import display, HTML

# suppress futurewarnings only
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
sns.set_theme(context='notebook', style='whitegrid')

# set default plot size
plt.rcParams['figure.figsize'] = 6,4

In [3]:
display(HTML("<style>.container { width:90% !important; }</style>"))

In [4]:
input_file = "kc_house_data.csv"
df = pd.read_csv(input_file)

## Data Preprocessing

In [5]:
df.drop(['id', 'lat','long','yr_renovated', 'view', 'waterfront', 'zipcode', 'date'], axis=1, inplace=True)
df.dropna()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,3,7,1180,0.0,1955,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,3,7,2170,400.0,1951,1690,7639
2,180000.0,2,1.00,770,10000,1.0,3,6,770,0.0,1933,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,5,7,1050,910.0,1965,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,3,8,1680,0.0,1987,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,360000.0,3,2.50,1530,1131,3.0,3,8,1530,0.0,2009,1530,1509
21593,400000.0,4,2.50,2310,5813,2.0,3,8,2310,0.0,2014,1830,7200
21594,402101.0,2,0.75,1020,1350,2.0,3,7,1020,0.0,2009,1020,2007
21595,400000.0,3,2.50,1600,2388,2.0,3,8,1600,0.0,2004,1410,1287
21596,325000.0,2,0.75,1020,1076,2.0,3,7,1020,0.0,2008,1020,1357

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21597 non-null  float64
 1   bedrooms       21597 non-null  int64
 2   bathrooms      21597 non-null  float64
 3   sqft_living    21597 non-null  int64
 4   sqft_lot       21597 non-null  int64
 5   floors         21597 non-null  float64
 6   condition      21597 non-null  int64
 7   grade          21597 non-null  int64
 8   sqft_above     21597 non-null  int64
 9   sqft_basement  21597 non-null  object
 10  yr_built       21597 non-null  int64
 11  sqft_living15  21597 non-null  int64
 12  sqft_lot15     21597 non-null  int64
dtypes: float64(3), int64(9), object(1)
memory usage: 2.1+ MB

In [7]:
df.sample(10)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
2548,265000.0,4,1.5,1740,12728,1.0,4,7,1180,560.0,1964,1830,11125
2771,509250.0,3,2.5,2100,7600,1.0,4,7,1450,650.0,1980,2010,7600
4570,319000.0,2,1.0,960,4400,1.0,4,7,960,0.0,1951,1520,5000
17177,997950.0,4,3.5,4270,117176,2.0,3,9,4270,0.0,2008,2610,5251
10359,429000.0,3,2.5,1860,11122,2.0,3,8,1860,0.0,1994,2420,8542
4584,268000.0,3,2.5,1850,6676,2.0,3,7,1850,0.0,1986,1700,6663
332,295000.0,3,2.0,1810,10530,1.0,3,8,1810,0.0,1991,1910,10450
18662,262000.0,5,1.0,1870,7800,1.0,3,7,1580,290.0,1962,1740,7808
18619,707900.0,3,1.0,1750,5355,2.0,4,7,1750,0.0,1929,2240,4590
7838,1210000.0,4,3.5,4560,16643,1.0,3,12,2230,2330.0,1995,4060,15177