# Project 2

#### Kyan and Rene

This will be a study on housing prices.

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier, export_graphviz, plot_tree
from sklearn.model_selection import learning_curve, GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn import tree
from IPython.display import display, HTML

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor


# suppress futurewarnings only
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [21]:
sns.set_theme(context='notebook', style='whitegrid')

# set default plot size
plt.rcParams['figure.figsize'] = 6,4

In [22]:
display(HTML("<style>.container { width:90% !important; }</style>"))

In [23]:
input_file = "kc_house_data.csv"
df = pd.read_csv(input_file)

## Data Preprocessing

In [24]:
df.drop(['id', 'lat','long','yr_renovated', 'view', 'waterfront', 'zipcode', 'date'], axis=1, inplace=True)
df.dropna()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,3,7,1180,0.0,1955,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,3,7,2170,400.0,1951,1690,7639
2,180000.0,2,1.00,770,10000,1.0,3,6,770,0.0,1933,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,5,7,1050,910.0,1965,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,3,8,1680,0.0,1987,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,360000.0,3,2.50,1530,1131,3.0,3,8,1530,0.0,2009,1530,1509
21593,400000.0,4,2.50,2310,5813,2.0,3,8,2310,0.0,2014,1830,7200
21594,402101.0,2,0.75,1020,1350,2.0,3,7,1020,0.0,2009,1020,2007
21595,400000.0,3,2.50,1600,2388,2.0,3,8,1600,0.0,2004,1410,1287
21596,325000.0,2,0.75,1020,1076,2.0,3,7,1020,0.0,2008,1020,1357

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21597 non-null  float64
 1   bedrooms       21597 non-null  int64
 2   bathrooms      21597 non-null  float64
 3   sqft_living    21597 non-null  int64
 4   sqft_lot       21597 non-null  int64
 5   floors         21597 non-null  float64
 6   condition      21597 non-null  int64
 7   grade          21597 non-null  int64
 8   sqft_above     21597 non-null  int64
 9   sqft_basement  21597 non-null  str
 10  yr_built       21597 non-null  int64
 11  sqft_living15  21597 non-null  int64
 12  sqft_lot15     21597 non-null  int64
dtypes: float64(3), int64(9), str(1)
memory usage: 2.1 MB

In [26]:
df.sample(10)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
7245,7700000.0,6,8.00,12050,27600,2.5,4,13,8570,3480.0,1910,3940,8800
2344,520000.0,3,2.50,2280,58712,2.5,3,9,2280,0.0,1987,2240,24332
5741,267000.0,3,2.25,2510,9900,1.0,3,8,1610,900.0,1978,1940,8510
11403,590000.0,4,2.25,2430,32496,1.0,3,9,2430,0.0,1993,2750,35506
7172,470000.0,4,1.75,1650,7276,1.0,3,7,1010,640.0,1977,1840,8550
20684,564950.0,4,2.75,2990,4521,2.0,3,7,2990,0.0,2014,2580,7539
19554,619790.0,3,1.75,1040,5097,1.0,4,7,800,240.0,1944,1630,5097
7091,395000.0,4,3.00,1980,7931,1.0,4,7,1160,820.0,1983,1910,7931
5781,1010000.0,4,2.50,3760,29224,2.0,3,11,3760,0.0,1987,3930,19916
11687,191950.0,2,2.50,1390,1302,2.0,3,7,1390,0.0,1987,1390,2052

In [28]:



predictors = ['bedrooms', 'condition', 'grade']
target = 'price'
X = df[predictors].values
y = df[target].values

# split the data into training and testing sets
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.3, random_state = 42)

# compute the most common price in the training set
most_common_price = pd.Series(y_train).value_counts().index[0]
print("Most common price in the training set:", most_common_price)

# compute and print the baseline accuracy
baseline_accuracy = (y_train == most_common_price).mean()
print(f"Baseline accuracy: {baseline_accuracy:.3f}")

# scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# create and fit the KNN regressor
clf = KNeighborsRegressor(n_neighbors=3)
clf.fit(X_train, y_train)

# predicted prices based on the selected predictor variables
y_pred = clf.predict(X_test)

# compute and print the accuracy of the model
accuracy = np.mean(y_pred == y_test)
print(f"Model accuracy: {accuracy:.3f}")

# printing the first 10 predicted prices
print(f'First 10 predicted prices: {y_pred[:10]}')

Most common price in the training set: 350000.0
Baseline accuracy: 0.008
Model accuracy: 0.000
First 10 predicted prices: [ 233333.33333333  335000.          401166.66666667  530000.
  454150.          398800.          368891.66666667 1399983.33333333
  287383.33333333  401166.66666667]