# Project 2

#### Kyan and Rene

This will be a study on housing prices.

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier, export_graphviz, plot_tree
from sklearn.model_selection import learning_curve, GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn import tree
from IPython.display import display, HTML

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# suppress futurewarnings only
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [5]:
sns.set_theme(context='notebook', style='whitegrid')

# set default plot size
plt.rcParams['figure.figsize'] = 6,4

In [6]:
display(HTML("<style>.container { width:90% !important; }</style>"))

In [7]:
input_file = "kc_house_data.csv"
df = pd.read_csv(input_file)

## Data Preprocessing

In [8]:
df.drop(['id', 'lat','long','yr_renovated', 'view', 'waterfront', 'zipcode', 'date'], axis=1, inplace=True)
df.dropna()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,3,7,1180,0.0,1955,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,3,7,2170,400.0,1951,1690,7639
2,180000.0,2,1.00,770,10000,1.0,3,6,770,0.0,1933,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,5,7,1050,910.0,1965,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,3,8,1680,0.0,1987,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,360000.0,3,2.50,1530,1131,3.0,3,8,1530,0.0,2009,1530,1509
21593,400000.0,4,2.50,2310,5813,2.0,3,8,2310,0.0,2014,1830,7200
21594,402101.0,2,0.75,1020,1350,2.0,3,7,1020,0.0,2009,1020,2007
21595,400000.0,3,2.50,1600,2388,2.0,3,8,1600,0.0,2004,1410,1287
21596,325000.0,2,0.75,1020,1076,2.0,3,7,1020,0.0,2008,1020,1357

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21597 non-null  float64
 1   bedrooms       21597 non-null  int64
 2   bathrooms      21597 non-null  float64
 3   sqft_living    21597 non-null  int64
 4   sqft_lot       21597 non-null  int64
 5   floors         21597 non-null  float64
 6   condition      21597 non-null  int64
 7   grade          21597 non-null  int64
 8   sqft_above     21597 non-null  int64
 9   sqft_basement  21597 non-null  str
 10  yr_built       21597 non-null  int64
 11  sqft_living15  21597 non-null  int64
 12  sqft_lot15     21597 non-null  int64
dtypes: float64(3), int64(9), str(1)
memory usage: 2.1 MB

In [10]:
df.sample(10)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,sqft_living15,sqft_lot15
10748,470000.0,3,2.50,2480,5082,2.0,3,7,2480,0.0,2004,2480,5874
2259,273000.0,2,0.50,1180,7750,1.0,4,6,590,590.0,1945,1380,8976
17930,906000.0,3,2.50,2030,1800,3.0,3,9,2030,0.0,2013,1450,1441
562,880000.0,3,2.50,2870,5163,2.0,3,9,2870,0.0,2014,1630,7995
11909,525000.0,1,1.00,830,3200,1.0,3,7,830,0.0,1924,1350,2512
2840,375000.0,3,1.75,1430,10574,2.0,3,7,1430,0.0,1981,1900,10450
17876,440000.0,3,1.75,2100,29735,1.0,4,7,1080,1020.0,1957,2100,11250
18548,675000.0,4,2.25,2760,12100,2.0,4,9,2760,0.0,1976,2850,12410
6704,549900.0,4,3.50,3420,4751,2.0,3,10,3420,0.0,2003,3490,5700
12482,660000.0,3,2.00,2080,5750,1.0,5,7,1040,?,1926,1710,4830

In [ ]:
predictors = ['bedrooms', 'condition', 'grade']
target = 'price'
X = df[predictors].values
y = df[target].values

# split the data into training and testing sets
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.3, random_state = 42)

# scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# create classifier object
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

# predicted prices based on the selected predictor variables
y_pred = clf.predict(X_test)

# printing the first 10 predicted prices
print(y_pred[:10])

[160000. 235000. 245000. 410000. 350000. 240000. 175000. 799950. 212000.
 245000.]